--- #YAML:1.0
name:               Mobile-Wurfl
version:            1.09
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI::Lite:            0
    Data::Dumper:         0
    DBD::mysql:           0
    DBD::SQLite:          0
    DBI:                  0
    ExtUtils::MakeMaker:  0
    File::Basename:       0
    File::Find:           0
    File::Path:           0
    File::Spec:           0
    FindBin:              0
    HTTP::Date:           0
    IO::Uncompress::Gunzip:  0
    IO::Uncompress::Unzip:  0
    LWP::UserAgent:       0
    Template:             0
    Test::More:           0
    XML::Parser:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
