# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mobile-Wurfl
version:      1.05
version_from: lib/Mobile/Wurfl.pm
installdirs:  site
requires:
    Array::Compare:                0
    CGI::Lite:                     0
    Data::Dumper:                  0
    DBD::mysql:                    0
    DBI:                           0
    ExtUtils::MakeMaker:           0
    File::Find:                    0
    File::Path:                    0
    FindBin:                       0
    LWP::UserAgent:                0
    Test::More:                    0
    XML::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
